include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - reference/**

linter:
  rules:
    avoid_print: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
