// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlX9zC8sOdlGoM5608rMFPrNem0kqDIjA',
    appId: '1:903635434365:web:411838c659c5ce0114ea14',
    messagingSenderId: '903635434365',
    projectId: 'fir-messaging-handler',
    authDomain: 'fir-messaging-handler.firebaseapp.com',
    storageBucket: 'fir-messaging-handler.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa4Q9ptI5Cv_RgELw1BkWyQN5xnPIN6ig',
    appId: '1:903635434365:android:a737481e2d7317e114ea14',
    messagingSenderId: '903635434365',
    projectId: 'fir-messaging-handler',
    storageBucket: 'fir-messaging-handler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT3A-vr1RTomhnLOJJr5JC6uovW0GHHyI',
    appId: '1:903635434365:ios:459b3dc8306096f814ea14',
    messagingSenderId: '903635434365',
    projectId: 'fir-messaging-handler',
    storageBucket: 'fir-messaging-handler.firebasestorage.app',
    iosBundleId: 'qoder.flutter.fmhexample',
  );
}
