name: fcm_tester
description: A CLI tool to test Firebase Messaging scenarios.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  dotenv: ^4.1.0
